# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15hHbJEd2SQ6ENDllLji7OKJc2KYbVr2P
"""

import os
from dotenv import load_dotenv

# Загрузка токена из .env
load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("8056440693:AAGOq8mgh5ffAnKks8F-FyX9H0BoVzg6Qxo")

# Путь к базе данных
DATA_PATH = "parsed_data.json"

# Настройки модели
MODEL_NAME = "IlyaGusev/saiga_mistral_7b"
MESSAGE_TEMPLATE = "<s>{role}\n{content}</s>"
RESPONSE_TEMPLATE = "<s>bot\n"

SYSTEM_PROMPT = """Ты – чат-бот консультант интернет-магазина кроссовок. Твоя задача — помочь клиенту выбрать наиболее подходящие кроссовки на основе его запроса.

У тебя есть доступ к базе данных из 836 моделей кроссовок. Каждая запись содержит:
- Название модели
- Описание
- Цену
- Доступные размеры
- Ссылку

Если клиент спрашивает про конкретную модель — найди её по названию или артикулу и дай полное описание.
Если клиент описывает характеристики (например, «ищу мужские кроссовки до 10 000 рублей») — подбери 1–3 наиболее подходящих варианта из базы данных.

Если информации недостаточно для ответа — скажи: 
"К сожалению, я не могу найти подходящую информацию. Пожалуйста, уточните ваш запрос."""""